### ISSUE TITLE
Torch==1.8.2 does not find a matching distribution

### ISSUE THREAD

**Issue by diaz994** [alfassy/FETA#2]
Hi - I attempted to run the following command: `pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111`

The error it threw back was:

ERROR: Could not find a version that satisfies the requirement torch==1.8.2 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.8.2

It seems that the distribution put on the documentation does not exist.

**Comment by alfassy** [comment]
I can't reproduce this error. sorry :(
